# Site settings
title:          "notes to self"
description:    "A smörgåsbord of programming, computer graphics, linux and \
                 web dev musings by Matthew Chigira. \
                 My venerable \"notes to self\"."
baseurl:        ""
url:            "https://nts.chigira.me"

# Author
author:
  name:         Matthew Chigira
  url:          https://nts.chigira.me

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, config.ru, Procfile ]
